name: quantum-transformers
dependencies:
  - python=3.10
  - pip
  - pip:
    - jupyterlab
    - ipywidgets
    - numpy
    - matplotlib
    - gdown
    - scikit-learn
    - torch
    - torchvision
    - torchtext
    - pennylane